name: Python Test CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches: 
      - dev
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    environment:
      name: test

    env:
      SERVER_PORT: ${{ vars.SERVER_PORT }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PW: ${{ secrets.POSTGRES_PW }}

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync test resources
        run: |
          aws s3 sync s3://${{ secrets.AWS_S3_BUCKET_NAME }}/test_resources/ test/resources/mockdata/
          
      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Run tests with pytest
        run: |
          uv run pytest